### PR TITLE
Added DNN-Based-Face-Detector and udpated contributors' list.

### PR DESCRIPTION
**Pull request by kgautam01**

### CODE REVIEW

**Comment by hvijaycse** [comment]
Hey there. @kgautam01 great work, but there seem to have same conflict in Contributor.md and  Automated_Essay_Score, i think you created two pull request for Automated_Essay_Score, I can't merge your Pull Request till you resolve conflicts,

Also you don't need to create a new PR for making changes just make changes and commit it your repo, all the changes will also be updated in this same PR.

**Comment by kgautam01** [comment]
I updated contributors.md file and created a single PR for DNN based face detector and this update. Just one PR was created for the Automated essay scorer. I am not able to understand the conflict here. Kindly help out.

**Comment by hvijaycse** [comment]
Problem was created by your previous PR in which you created new file `Automated_Essay_Scorer`, this was the main issue causing conflict, I reverted back your last Pull Request, I hope that it doesn't affect you hacktoberfest , if it does just make a new pr and I will accept it immediately.

**Comment by kgautam01** [comment]
It seems the issue has been resolved and PR has been merged already by you.
No need to do anything from my end then?

**Comment by hvijaycse** [comment]
Yup, everything is fine now.

**Comment by kgautam01** [comment]
Thanks a lot.

**Pull request merged**
